# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/oxsecurity/megalinter
    rev: v8.5.0
    hooks:
      - id: megalinter-incremental
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.22.0
    hooks:
      - id: commitlint
        stages:
          - pre-commit
        additional_dependencies:
          - "@commitlint/config-conventional"
        args:
          - -x
          - "@commitlint/config-conventional"
